Merge 4.3.3 into master
wazuh/wazuh-kubernetes pull request #268
Opened 2022-06-01 18:53 UTC by vcerenu

This PR merge Wazuh 4.3.3 version into master branch

2022-06-01 18:56 UTC, teddytpc1 requested changes

2022-06-01 18:56 UTC, teddytpc1 commented on CHANGELOG.md
> +- Update to Wazuh version [4.4.0](https://github.com/wazuh/wazuh/blob/v4.4.0/CHANGELOG.md#v440)## [4.3.3]
Add line break.

2022-06-01 19:20 UTC, teddytpc1 approved these changes

2022-06-02 09:04 UTC, okynos approved these changes

2022-06-02 09:04 UTC, merged