EKS cluster deployment
wazuh/wazuh-kubernetes pull request #298
Opened 2022-08-30 12:26 UTC by teddytpc1

This PR closes #274.

2022-08-30 12:32 UTC, vcerenu submitted a review, later dismissed
LGTM

2022-08-31 08:26 UTC, okynos requested changes
Really cool stuff, minor change, thanks.

2022-08-31 08:26 UTC, okynos commented on deploy_eks_cluster/README.md
> +1. Define whether you will use an existing VPN.
```suggestion
1. Define whether you will use an existing VPC.
```

2022-09-01 14:11 UTC, okynos submitted a review, later dismissed

2022-09-06 13:45 UTC, gdiazlo requested changes
I think we need to include more information in the README. The goal of the issue was to let our users know how and why we do this to test Wazuh in a EKS cluster.

2022-09-06 13:45 UTC, gdiazlo commented on deploy_eks_cluster/README.md
> +1. Define whether you will use an existing VPC.
1. Select one of the following templates:
  a. `cluster.yml` If you need to create a VPC
  b. `cluster_existing_vpc.yml` If you already have a VPC

2022-09-06 13:45 UTC, gdiazlo commented on deploy_eks_cluster/README.md
> +2. Replace the values marked with `<>`.
2. Configure the template replacing the values marked with '<>':

2022-09-06 13:45 UTC, gdiazlo commented on deploy_eks_cluster/README.md
> +Deploy an EKS Cluster for Wazuh.
These instructions describe how we create an EKS cluster to deploy Wazuh. The files and configurations presented here are what we use to test whether Wazuh works as it should in Kubernetes. 

Because there are many ways to deploy applications and services on Kubernetes, you can take these instructions as a starting point, and adapt them to your environment.

2022-09-06 13:45 UTC, gdiazlo commented on deploy_eks_cluster/README.md
> +
I would add a diagram about what it looks like when everything is running, so anyone can see the shape of the deployment.

Something in the lines of: https://d1.awsstatic.com/partner-network/QuickStart/datasheets/amazon-eks-on-aws-architecture-diagram.7fdf06380021e6dc7c622d298d99e3c1154163bc.png

2022-09-06 13:45 UTC, gdiazlo commented on deploy_eks_cluster/README.md
> +## YAML files
Because this is also explained in the Deploy section, I would erase this section.

2022-09-06 13:45 UTC, gdiazlo commented on deploy_eks_cluster/README.md
> +The goal of this section is to simplify the creation of an EKS cluster.
This phrase here does not make sense. This section is describing the resources the templates are going to create.

2022-09-06 13:45 UTC, gdiazlo commented on deploy_eks_cluster/README.md
> +The execution of this guide will create 2 Cloudformation stacks with the following resources:
Why are we using two cloudformation stacks, all the resources are duplicated on each stack. We need to explain the motivation behind this setup.

2022-09-06 13:45 UTC, gdiazlo commented on deploy_eks_cluster/README.md
> +The execution of this guide will create 2 Cloudformation stacks with the following resources:
Also, we need to describe what instances we are using and why.

2022-09-06 18:03 UTC, teddytpc1 commented on deploy_eks_cluster/README.md
> +The execution of this guide will create 2 Cloudformation stacks with the following resources:
The resources are not duplicated. Eksctl creates two stacks. We can specify which resources are created in each stack.

2022-09-06 18:04 UTC, teddytpc1 commented on deploy_eks_cluster/README.md
> +The goal of this section is to simplify the creation of an EKS cluster.
You are right. I will move it.

2022-09-08 09:58 UTC, gdiazlo commented on deploy_eks_cluster/README.md
> +The execution of this guide will create 2 Cloudformation stacks with the following resources:
I see. It would be good to say why chose these resources and stacks particularly. If we based this configuration on other documentation / best-practice from AWS, I would mention it here, something like:

_Following the AWS documentation [link] related to EKS deployment, our deployment files will generate the following AWS resources:_

Also, I would indicate the size of the EC2 instances we are going to create.

2022-09-08 11:43 UTC, teddytpc1 commented on deploy_eks_cluster/README.md
> +The execution of this guide will create 2 Cloudformation stacks with the following resources:
We just choose it because it creates a basic EKS Cluster with all the needed resources for Wazuh to work. And also it is a simple way to deploy it.
The instances type is specified [here](https://github.com/wazuh/wazuh-kubernetes/blob/274-k8s-cluster-deployment/deploy_eks_cluster/README.md#deployment) (step 3).

2022-10-05 17:39 UTC, vcerenu approved these changes
LGTM

2022-10-06 07:40 UTC, gdiazlo approved these changes
lgtm

2023-04-27 17:40 UTC, cyberresearch-us commented
Just curious if/when this will be merged.

2023-05-03 17:40 UTC, c-bordon approved these changes
LGTM

2023-05-03 18:07 UTC, merged